OPENAI_API_KEY = "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"
GOOGLE_API_KEY = "AIzaSyC2mv4I0K5-r_itOXU9FQDjXQC0vaU-jiY"
PINECONE_API_KEY = "c58d9979-cd72-4771-bddf-356cb86e35a3"
SENDGRID_API_KEY = "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"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppYWlzbnliamhramNicHJ4YXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTE1NDE5MjIsImV4cCI6MjAyNzExNzkyMn0.dflTXwGuz0U8SKzZwPUUl3D9EkloJFLzI41OT-wnbng"

[accounts]
users = [
  { username = "george.jen", password = "2024" },
  { username = "lam.dao", password = "2024" }
]
[admin_accounts]
users = [
  { username = "glen.qin", password = "2024" },
  { username = "lam.dao", password = "2024" }
]

